services:
  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8081:8081"
    volumes:
      - ./gateway/src:/usr/src/app/src
      - ./gateway/src/main/resources/application.yml:/usr/src/app/src/main/resources/application.yml
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - auth-service
    networks:
      - ecommerce
  auth-service:
    build: 
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3000:3000"
    volumes:
      - ./services/auth-service:/usr/src/app
      - ./services/auth-service/node_modules:/usr/src/app/node_modules
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge