spring:
  application:
    name: gateway
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      exclude: "**/static/**"
    livereload:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://auth-service:3000
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /auth/${segment}

server:
  port: 8081
